#!/usr/bin/env bun
/** Renders Formula/tomtom.rb for the Homebrew tap from per-platform release checksums. */
import { writeFileSync } from "node:fs";

interface Args {
  readonly version: string;
  readonly repo: string;
  readonly darwinArm64: string;
  readonly darwinX64: string;
  readonly linuxX64: string;
  readonly linuxArm64: string;
  readonly out: string;
}

const parseArgs = (argv: ReadonlyArray<string>): Args => {
  const flags = new Map<string, string>();
  for (const arg of argv) {
    const match = arg.match(/^--([a-z0-9-]+)=(.*)$/);
    if (match?.[1] !== undefined && match[2] !== undefined) flags.set(match[1], match[2]);
  }
  const require = (name: string): string => {
    const value = flags.get(name);
    if (!value) throw new Error(`missing required --${name}`);
    return value;
  };
  return {
    version: require("version"),
    repo: require("repo"),
    darwinArm64: require("darwin-arm64"),
    darwinX64: require("darwin-x64"),
    linuxX64: require("linux-x64"),
    linuxArm64: require("linux-arm64"),
    out: require("out"),
  };
};

const render = (args: Args): string => {
  const base = `https://github.com/${args.repo}/releases/download/v${args.version}`;
  return `# generated by scripts/generate-formula.ts — do not edit by hand
class Tomtom < Formula
  desc "Unix-friendly CLI for TomTom's location APIs"
  homepage "https://github.com/${args.repo}"
  version "${args.version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${base}/tomtom-darwin-arm64.tar.gz"
      sha256 "${args.darwinArm64}"
    end
    on_intel do
      url "${base}/tomtom-darwin-x64.tar.gz"
      sha256 "${args.darwinX64}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/tomtom-linux-arm64.tar.gz"
      sha256 "${args.linuxArm64}"
    end
    on_intel do
      url "${base}/tomtom-linux-x64.tar.gz"
      sha256 "${args.linuxX64}"
    end
  end

  def install
    bin.install "tomtom"
  end

  test do
    system "#{bin}/tomtom", "--version"
  end
end
`;
};

const args = parseArgs(process.argv.slice(2));
writeFileSync(args.out, render(args));
console.log(`Wrote ${args.out}`);
